services:
  db:
    image: postgres:13
    restart: 'always'
    container_name: integration-testing-prisma
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=dbname
